# Generated by Django 5.0 on 2024-02-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'товар в заказе', 'verbose_name_plural': 'товары в заказах'},
        ),
    ]
